[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "GZnUtzwNfMrsK7U9NZT1PwrgnUnu6z9cGwc1v1Q7e5ta"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/lukas/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"

