[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "61qV1VXxLZPDD8dsxvnRGg3bT2BZ8AvcQMRmzAVzVn6R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/lukas/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
